### ISSUE TITLE
CSRF Token

### ISSUE THREAD

**Issue by dhruvika29kevat** [nilp06/online-freelance-marketplace#3]
Started POST "/users/sign_in" for ::1 at 2023-07-06 10:24:23 +0530
Processing by Devise::SessionsController#create as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"email"=>"nil.p@gmail.com", "password"=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Log in"}
Can't verify CSRF token authenticity.
Completed 422 Unprocessable Entity in 1ms (ActiveRecord: 0.0ms | Allocations: 859)

 

ActionController::InvalidAuthenticityToken (Can't verify CSRF token authenticity.):

**Comment by nilp06** [comment]
solved
